language: R
sudo: required
cache: packages

os: 
  - linux
  - osx
  
before_install:
  - if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then brew cask install libreoffice ; fi  
  - if [[ "${TRAVIS_OS_NAME}" = "linux" ]]; then sudo apt-get update -y && sudo apt-get install libreoffice-core; fi

after_success:
  - Rscript -e 'covr::codecov()'
